### ISSUE TITLE
Is it possible to make a travis-ci configuration for projects using this 3DS SDL1.2 (like SDLPal 3DS)?

### ISSUE THREAD

**Issue by PalMusicFan** [zephray/SDL-1.2#1]
Is it possible to make a travis-ci configuration for projects using this 3DS SDL1.2 (like SDLPal 3DS)?
Thanks so much!

**Comment by zephray** [comment]
Yes it is possible. I have written a travis-ci configuration for SDLPal 3DS in my own fork. See https://github.com/zephray/sdlpal/blob/master/.travis.yml

**Comment by PalMusicFan** [comment]
Sorry for reopening this issue. 
Would you please make a new group of banner.bin, icon.bin, icon.png and icon_24x24.png without SOFTSTAR's copyright images (and send a pull request)? 
Thanks so much!

**Comment by zephray** [comment]
Sorry for the late reply, I was busy and I totally forgot about this. The original icon.png and icon_24x24.png are redrawn myself, I think it shouldn't cause any problem? (https://github.com/zephray/sdlpal-old/blob/master/3ds/icon.png). banner.bin and banner.png are problematic, though. I am not sure what to put there without using copyrighted materials...

**Comment by PalMusicFan** [comment]
Well, I have no idea either, especially considering there should be a wave clip. 
Do you think it is reasonable to add banner-making steps to our travis-ci configuration? I have tried bannertool (https://github.com/Steveice10/bannertool) , seems that it works well.
